version: '3.7'
services:
  backend:
    build: 
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - db
    networks:
      - app
    command: bash -c "php artisan migrate:refresh --seed && php artisan serve --host=0.0.0.0"

  queue:
    build: 
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 8001:8000
    depends_on:
      - db
      - backend
    networks:
      - app
    command: ["supervisord", "-c", "/etc/supervisord.conf"]
    # The below environment variables are used in the supervisord.conf file to run the queue worker through supervisor
    environment:
      - APP_ROOT= /app/api
      - QUEUE_DRIVER= database
      # - NUM_PROCS=${NUM_PROCS}

  scheduler:
    build: 
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 8002:8000
    depends_on:
      - db
      - backend
    networks:
      - app
    command: php artisan schedule:work

  frontend:
    build: 
      context: ./front
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - backend
    networks:
      - app
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - 3400:80
    depends_on:
      - db
    networks:
      - app

  db:
    image: mysql:5.7.22
    environment:
      MYSQL_DATABASE: news-aggregator
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    networks:
      - app

networks:
  app:
    driver: bridge